Add missing browserify-shim dependency
Without this, bundling via browserify fails with:

```
Error: Cannot find module 'browserify-shim' from '/src/node_modules/pojoviz'
```